In [7]:
import numpy as np
import pandas as pd

### I.
#### 1.	Create 2- One dimensional Arrays and print sum of individual element and multiply each with 3

In [8]:
arr1 = np.array([1,1,0,0,1,1,0])
arr2 = np.array([1,1,1,0,1,0,1])

print("Array 1: ",arr1)
print("Array 2: ",arr2)

Array 1:  [1 1 0 0 1 1 0]
Array 2:  [1 1 1 0 1 0 1]


In [9]:
print("Sum of elements in array 1: ",np.sum(arr1))
print("Sum of elements in array 2: ",np.sum(arr2))

Sum of elements in array 1:  4
Sum of elements in array 2:  5


In [10]:
print("Array one after multiplying each element with 3: \n",arr1*3)
print("Array two after multiplying each element with 3: \n",arr2*3)

Array one after multiplying each element with 3: 
 [3 3 0 0 3 3 0]
Array two after multiplying each element with 3: 
 [3 3 3 0 3 0 3]


#### 2.	Manipulate Logical and, OR Not operations on Array

In [11]:
print("Logical AND operation on arrays:\n",np.logical_and(arr1,arr2))
print("Logical OR operation on arrays:\n",np.logical_or(arr1,arr2))
print("Logical NOT operation on first array:\n",np.logical_not(arr1))
print("Logical NOT operation on second array:\n",np.logical_not(arr2))

Logical AND operation on arrays:
 [ True  True False False  True False False]
Logical OR operation on arrays:
 [ True  True  True False  True  True  True]
Logical NOT operation on first array:
 [False False  True  True False False  True]
Logical NOT operation on second array:
 [False False False  True False  True False]


#### 3. 	Perform data Slicing Operations

In [12]:
print(arr1[1:4])
print(arr1[ : :-1])
print(arr1[-4:-2])
print(arr2[0:3])
print(arr2[2:-1])
print(arr2[:-1])

[1 0 0]
[0 1 1 0 0 1 1]
[0 1]
[1 1 1]
[1 0 1 0]
[1 1 1 0 1 0]


#### 4. Perform Boolean operations between arrays

In [13]:
print("Bitwise AND operation on arrays:\n",np.bitwise_and(arr1,arr2))
print("Bitwise OR operation on arrays:\n",np.bitwise_or(arr1,arr2))
print("Bitwise XOR operation on arrays:\n",np.bitwise_xor(arr1,arr2))
print("Bitwise LEFT SHIFT operation on first array after left shifting 1 bits:\n",np.left_shift(arr1,1))
print("Bitwise RIGHT SHIFT operation on first array after right shifting 1 bits:\n",np.right_shift(arr1,1))
print("Bitwise LEFT SHIFT operation on second array after left shifting 1 bits:\n",np.left_shift(arr2,1))
print("Bitwise RIGHT SHIFT operation on second array after right shifting 1 bits:\n",np.right_shift(arr2,1))

Bitwise AND operation on arrays:
 [1 1 0 0 1 0 0]
Bitwise OR operation on arrays:
 [1 1 1 0 1 1 1]
Bitwise XOR operation on arrays:
 [0 0 1 0 0 1 1]
Bitwise LEFT SHIFT operation on first array after left shifting 1 bits:
 [2 2 0 0 2 2 0]
Bitwise RIGHT SHIFT operation on first array after right shifting 1 bits:
 [0 0 0 0 0 0 0]
Bitwise LEFT SHIFT operation on second array after left shifting 1 bits:
 [2 2 2 0 2 0 2]
Bitwise RIGHT SHIFT operation on second array after right shifting 1 bits:
 [0 0 0 0 0 0 0]


### II.  Create 2- Two dimensional Arrays and print sum of individual element and multiply each with 3

In [14]:
arr1 = np.array([(1,1,1),(1,0,0),(0,1,0)])
arr2 = np.array([(1,0,1),(1,1,0),(0,0,0)])

print("Array 1:\n",arr1)
print("Array 2:\n",arr2)

Array 1:
 [[1 1 1]
 [1 0 0]
 [0 1 0]]
Array 2:
 [[1 0 1]
 [1 1 0]
 [0 0 0]]


In [15]:
print("Sum of elements in array 1: ",np.sum(arr1))
print("Sum of elements in array 2: ",np.sum(arr2))

Sum of elements in array 1:  5
Sum of elements in array 2:  4


In [16]:
print("Array after multiplying each element with 3:\n",arr1*3)
print("Array after multiplying each element with 3:\n",arr2*3)

Array after multiplying each element with 3:
 [[3 3 3]
 [3 0 0]
 [0 3 0]]
Array after multiplying each element with 3:
 [[3 0 3]
 [3 3 0]
 [0 0 0]]


#### 5.	Manipulate Logical and, OR Not operations on Array

In [17]:
print("Logical AND operation on arrays:\n",np.logical_and(arr1,arr2))
print("Logical OR operation on arrays:\n",np.logical_or(arr1,arr2))
print("Logical NOT operation on first array:\n",np.logical_not(arr1))
print("Logical NOT operation on second array:\n",np.logical_not(arr2))

Logical AND operation on arrays:
 [[ True False  True]
 [ True False False]
 [False False False]]
Logical OR operation on arrays:
 [[ True  True  True]
 [ True  True False]
 [False  True False]]
Logical NOT operation on first array:
 [[False False False]
 [False  True  True]
 [ True False  True]]
Logical NOT operation on second array:
 [[False  True False]
 [False False  True]
 [ True  True  True]]


#### 6.	Perform data Slicing Operations

In [18]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a[1:,1])
print(a[0:2])
print(a[-2:-1])
print(a[:,0:2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 8]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[[1 2]
 [4 5]
 [7 8]]


#### 7.	Perform Boolean operations between arrays

In [19]:
print("Bitwise AND operation on arrays:\n",np.bitwise_and(arr1,arr2))
print("Bitwise OR operation on arrays:\n",np.bitwise_or(arr1,arr2))
print("Bitwise XOR operation on arrays:\n",np.bitwise_xor(arr1,arr2))
print("Bitwise LEFT SHIFT operation on first array after left shifting 2 bits:\n",np.left_shift(arr1,2))
print("Bitwise RIGHT SHIFT operation on first array after right shifting 1 bits:\n",np.right_shift(arr1,1))
print("Bitwise LEFT SHIFT operation on second array after left shifting 3 bits:\n",np.left_shift(arr2,3))
print("Bitwise RIGHT SHIFT operation on second array after right shifting 1 bits:\n",np.right_shift(arr2,1))

Bitwise AND operation on arrays:
 [[1 0 1]
 [1 0 0]
 [0 0 0]]
Bitwise OR operation on arrays:
 [[1 1 1]
 [1 1 0]
 [0 1 0]]
Bitwise XOR operation on arrays:
 [[0 1 0]
 [0 1 0]
 [0 1 0]]
Bitwise LEFT SHIFT operation on first array after left shifting 2 bits:
 [[4 4 4]
 [4 0 0]
 [0 4 0]]
Bitwise RIGHT SHIFT operation on first array after right shifting 1 bits:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Bitwise LEFT SHIFT operation on second array after left shifting 3 bits:
 [[8 0 8]
 [8 8 0]
 [0 0 0]]
Bitwise RIGHT SHIFT operation on second array after right shifting 1 bits:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### III. 
- #### arange()

In [20]:
arr = np.arange(2,25,3)
print("Array formed using arange(start,end,step): ",arr)

Array formed using arange(start,end,step):  [ 2  5  8 11 14 17 20 23]


- #### reshape()

In [21]:
print("Array reshaped with 2 rows and 4 columns: \n",arr.reshape(2, 4))
print("Array reshaped with 4 rows and 2 columns: \n",arr.reshape(4, 2))
print("Original array reshaped to 3D : \n", arr.reshape(2, 2, 2)) 

Array reshaped with 2 rows and 4 columns: 
 [[ 2  5  8 11]
 [14 17 20 23]]
Array reshaped with 4 rows and 2 columns: 
 [[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]
Original array reshaped to 3D : 
 [[[ 2  5]
  [ 8 11]]

 [[14 17]
  [20 23]]]


- #### resize()

In [22]:
arr.resize(2,4)
print("Array reshaped to 2 rows and 4 colums permanently: \n",arr)

Array reshaped to 2 rows and 4 colums permanently: 
 [[ 2  5  8 11]
 [14 17 20 23]]


- #### hsplit()

In [23]:
arr = np.arange(16).reshape(4, 4) 
print(arr)
arr = np.hsplit(arr, 2) 
print(arr) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [24]:
arr = np.arange(27).reshape(3, 3, 3) 
print(arr)  
arr = np.hsplit(arr, 1) 
print(arr) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])]


- #### Extract ones, Two’s in arrays

In [25]:
arr = np.array([1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2])
unique, counts = np.unique(arr, return_counts=True)
print(dict(zip(unique, counts)))

{1: 8, 2: 7}


- #### Scalar()

In [26]:
# numpy.asscalar() function 
# creating a array of size 1 

arr = np.array([8]) 
print ("Input array : ", arr) 

scalar = np.asscalar(arr) 
print ("output scalar from input array : ", scalar) 

Input array :  [8]
output scalar from input array :  8


<ipython-input-26-1ccd15bcb92d>:7: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  scalar = np.asscalar(arr)


### IV. Create Data Frame with a MultiIndex

In [27]:
df=pd.DataFrame({"a":[1,2,3],
                 "b":[4,5,6],
                 "c":[7,8,9]},
                index=[1,2,3])
df

a  b  c
1  1  4  7
2  2  5  8
3  3  6  9

In [28]:
df=pd.DataFrame({1:[1,2,3],
                 2:[4,5,6],
                 3:[7,8,9]},
                index=["a","b","c"])
df

1  2  3
a  1  4  7
b  2  5  8
c  3  6  9

In [29]:
df=pd.DataFrame({"a":[1,2,3],
                 "b":[4,5,6],
                 "c":[7,8,9]},
                index=pd.MultiIndex.from_tuples([('d',1),('d',1),('e',2)],names=['n','v']))
df

a  b  c
n v         
d 1  1  4  7
  1  2  5  8
e 2  3  6  9

### V. import .CSV file do the following
(https://www.kaggle.com/aljarah/xAPI-Edu-Data- Students' Academic Performance Dataset)

In [30]:
edu_data = pd.read_csv("D:/KL University/SEM 2-2/Data Science/Labs/Lab 1/xAPI-Edu-Data.csv")
edu_data

gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father           15                16   
1           IT        F   Father           20                20   
2           IT        F   Father           10                 7   
3           IT        F   Father           30                25   
4           IT        F   Father           40                50   
..         ...      ...      ...          ...               ...   
475  Chemistry        S   Father            5                 4   
476    Geology        F   Father           50                77   
477    Geology        S   Father           55                74   
478    History        F   Father           30                17   
479    History        S   Father           35                14   

     AnnouncementsView  Discussion ParentAnsweringSurvey  \
0                    2          20                   Yes   
1                    3          25                   Yes   
2                    0          30                    No   
3                    5          35                    No   
4                   12          50                    No   
..                 ...         ...                   ...   
475                  5           8                    No   
476                 14          28                    No   
477                 25          29                    No   
478                 14          57                    No   
479                 23          62                    No   

    ParentschoolSatisfaction StudentAbsenceDays Class  
0                       Good            Under-7     M  
1                       Good            Under-7     M  
2                        Bad            Above-7     L  
3                        Bad            Above-7     L  
4                        Bad            Above-7     M  
..                       ...                ...   ...  
475                      Bad            Above-7     L  
476                      Bad            Under-7     M  
477                      Bad            Under-7     M  
478                      Bad            Above-7     L  
479                      Bad            Above-7     L  

[480 rows x 17 columns]

#### 1. describe()

In [31]:
edu_data.describe()

raisedhands  VisITedResources  AnnouncementsView  Discussion
count   480.000000        480.000000         480.000000  480.000000
mean     46.775000         54.797917          37.918750   43.283333
std      30.779223         33.080007          26.611244   27.637735
min       0.000000          0.000000           0.000000    1.000000
25%      15.750000         20.000000          14.000000   20.000000
50%      50.000000         65.000000          33.000000   39.000000
75%      75.000000         84.000000          58.000000   70.000000
max     100.000000         99.000000          98.000000   99.000000

#### 2. Mean()

In [32]:
edu_data.mean()

raisedhands          46.775000
VisITedResources     54.797917
AnnouncementsView    37.918750
Discussion           43.283333
dtype: float64

#### 3. Median()

In [33]:
edu_data.median()

raisedhands          50.0
VisITedResources     65.0
AnnouncementsView    33.0
Discussion           39.0
dtype: float64

#### 4. Slicing operations

In [34]:
edu_data[1:5]

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [35]:
edu_data[['gender','Topic']]

gender      Topic
0        M         IT
1        M         IT
2        M         IT
3        M         IT
4        M         IT
..     ...        ...
475      F  Chemistry
476      F    Geology
477      F    Geology
478      F    History
479      F    History

[480 rows x 2 columns]

In [36]:
edu_data.loc[4,:] # returned a series
edu_data.loc[[4],:] # return a dataframe

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
4          50                    No                      Bad   

  StudentAbsenceDays Class  
4            Above-7     M

In [37]:
edu_data.loc[0:4,:] # inclusive of b in a:b

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [38]:
edu_data.loc[:,['gender','Topic']]

gender      Topic
0        M         IT
1        M         IT
2        M         IT
3        M         IT
4        M         IT
..     ...        ...
475      F  Chemistry
476      F    Geology
477      F    Geology
478      F    History
479      F    History

[480 rows x 2 columns]

In [39]:
edu_data.loc[:,'gender':'Relation']

gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  
0           IT        F   Father  
1           IT        F   Father  
2           IT        F   Father  
3           IT        F   Father  
4           IT        F   Father  
..         ...      ...      ...  
475  Chemistry        S   Father  
476    Geology        F   Father  
477    Geology        S   Father  
478    History        F   Father  
479    History        S   Father  

[480 rows x 9 columns]

In [40]:
cols = ['raisedhands',
        'VisITedResources',
        'AnnouncementsView',
        'Discussion',
        'ParentAnsweringSurvey',
        'ParentschoolSatisfaction',
        'StudentAbsenceDays',
        'Class']
edu_data.head().drop(cols,axis=1)

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  
0        F   Father  
1        F   Father  
2        F   Father  
3        F   Father  
4        F   Father

In [41]:
#edu_data[edu_data.GradeID=='G-04'].ParentAnsweringSurvey # Chained Indexing
edu_data.loc[edu_data.GradeID=='G-04','ParentAnsweringSurvey']

0      Yes
1      Yes
2       No
3       No
4       No
5      Yes
12      No
249     No
250    Yes
251     No
252     No
253     No
254    Yes
255    Yes
256     No
257     No
258    Yes
259     No
260     No
261    Yes
262    Yes
263     No
290     No
291     No
292    Yes
293    Yes
294    Yes
295    Yes
296     No
297     No
298     No
299     No
300     No
301     No
302     No
303     No
304    Yes
305    Yes
306    Yes
307    Yes
308    Yes
309    Yes
310     No
311     No
312    Yes
313    Yes
314    Yes
315    Yes
Name: ParentAnsweringSurvey, dtype: object

In [42]:
edu_data.iloc[0:10,0:5] # exclusive of b in a:b

gender NationalITy PlaceofBirth       StageID GradeID
0      M          KW       KuwaIT    lowerlevel    G-04
1      M          KW       KuwaIT    lowerlevel    G-04
2      M          KW       KuwaIT    lowerlevel    G-04
3      M          KW       KuwaIT    lowerlevel    G-04
4      M          KW       KuwaIT    lowerlevel    G-04
5      F          KW       KuwaIT    lowerlevel    G-04
6      M          KW       KuwaIT  MiddleSchool    G-07
7      M          KW       KuwaIT  MiddleSchool    G-07
8      F          KW       KuwaIT  MiddleSchool    G-07
9      F          KW       KuwaIT  MiddleSchool    G-07